### ISSUE TITLE
DateFormatter error in `gnss_plots` 

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics-nodes#1]
I'm not sure if the bags that cause this error have some strange data in it. Please provide instructions on what info you would need to further debug this.

```
2016-10-02 13:46:40,352 WARNING marv.node.gnss_plots f2b14c7f-c885-4825-bd33-d0f07649717d No orientations found
2016-10-02 13:46:40,708 ERROR marv.node.gnss_plots f2b14c7f-c885-4825-bd33-d0f07649717d error
Traceback (most recent call last):
  File "/marv/venv/local/lib/python2.7/site-packages/marv/_aggregate.py", line 278, in update
    value = node(self)
  File "/marv/venv/local/lib/python2.7/site-packages/marv/_node.py", line 103, in __call__
    rv = self.node_func(**inputs)
  File "/marv/venv/local/lib/python2.7/site-packages/marv/_node.py", line 57, in __call__
    return self.func(*args, **kw)
  File "/marv/venv/local/lib/python2.7/site-packages/marv_robotics/nodes/gnss.py", line 189, in gnss_plots
    positions[ptopic], orientations[otopic])
  File "/marv/venv/local/lib/python2.7/site-packages/marv_robotics/nodes/gnss.py", line 112, in render
    fig.savefig(plt_path)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1557, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2237, in print_figure
    **kwargs)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 593, in print_jpg
    buf, size = self.print_to_buffer()
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 562, in print_to_buffer
    FigureCanvasAgg.draw(self)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 463, in draw
    self.figure.draw(self.renderer)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1129, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2384, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/axis.py", line 1126, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/axis.py", line 959, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/axis.py", line 906, in iter_ticks
    for i, val in enumerate(majorLocs)]
  File "/marv/venv/local/lib/python2.7/site-packages/matplotlib/dates.py", line 464, in __call__
    raise ValueError('DateFormatter found a value of x=0, which is '
ValueError: DateFormatter found a value of x=0, which is an illegal date.  This usually occurs because you have not informed the axis that it is plotting dates, e.g., with ax.xaxis_date()
```

**Comment by NikolausDemmel** [comment]
I can confirm this still happens in 2.0.0b1.

**Comment by chaoflow** [comment]
We have not seen this in a while. In case this happens again, please create an issue for [marv robotics](https://github.com/ternaris/marv-robotics/issues), ideally with a small example bag attached.
